pull_request_rules:
  - name: Automatic merge
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - "status-success=build"
    actions:
      merge:
        strict: true
  - name: Merge scala-steward
    conditions:
      - base=master
      - author=scala-steward
      - "status-success=build"
    actions:
      merge:
        strict: true
