version: 2
jobs:
  test:
    docker:
      - image: hseeberger/scala-sbt:8u181_2.12.8_1.2.8
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: cd scalafix && sbt scalafmtCheckAll && sbt tests/test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  release:
    docker:
      - image: hseeberger/scala-sbt:8u181_2.12.8_1.2.8
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: sbt-cache
      - run: echo -n "${PGP_PUBLIC}" | base64 -d > /tmp/public.asc
      - run: echo -n "${PGP_SECRET}" | base64 -d > /tmp/secret.asc
      - run: cd scalafix && sbt rules/releaseEarly

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          context: Sonatype
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
