name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: sbt scalafmtCheckAll
    - name: Test
      run: sbt tests/test
